name: Cloud Platform Deploy
description: Deploy to Cloud Platform using Helm
inputs:
  version:
    description: The version of the service to deploy
    required: true
  api:
    description: The KUBE_ENV_API
    required: true
  cert:
    description: The KUBE_CERT
    required: true
  cluster:
    description: The KUBE_CLUSTER
    required: true
  namespace:
    description: The KUBE_NAMESPACE
    required: true
  token:
    description: The KUBE_TOKEN
    required: true
  gh_auth_token:
    description: Auth token for Github
    required: true
  github_org:
    description: The github org in which the runners are deployed
    required: true
  runner_label:
    description: The labels for the runners
    required: true
  runner_group:
    description: The runner group for the runners
    required: true  

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6.0.2
    - name: Authenticate
      uses: ./.github/actions/cloud-platform-auth
      with:
        api: ${{ inputs.api }}
        cert: ${{ inputs.cert }}
        cluster: ${{ inputs.cluster }}
        namespace: ${{ inputs.namespace }}
        token: ${{ inputs.token }}

    - name: Deploy
      shell: bash
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install helm
        yq -i ".appVersion = \"${{ inputs.version }}\"" "helm_deploy/${{ github.event.repository.name }}/Chart.yaml"
        exec helm upgrade '${{ github.event.repository.name }}' 'helm_deploy/${{ github.event.repository.name }}' \
          --rollback-on-failure \
          --history-max 10 \
          --install \
          --reset-values \
          --set 'image.tag=${{ inputs.version }}' \
          --set 'version=${{ inputs.version }}' \
          --timeout 10m \
          --wait \
          --set env.GH_AUTH_TOKEN="${{ inputs.gh_auth_token }}" \
          --set env.RUNNER_LABEL="${{ inputs.runner_label }}" \
          --set env.RUNNER_GROUP="${{ inputs.runner_group }}" \
          --set env.GH_ORG="${{ inputs.github_repository }}"         
