name: Build Docker image
description: Build, and optionally push, a Docker image

inputs:
  project:
    description: Project name
  dockerfile:
    description: Dockerfile path
    default: Dockerfile
  push:
    description: Whether to push images to the registry
    default: 'false'
  version:
    description: Version
  gh_auth_token:
    description: GitHub token

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build Docker images
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ${{ inputs.dockerfile}}
        push: ${{ inputs.push }}
        provenance: false
        tags: |
          ghcr.io/ministryofjustice/${{ inputs.project }}:latest
          ghcr.io/ministryofjustice/${{ inputs.project }}:${{ inputs.version }}
      env:
        GH_AUTH_TOKEN: ${{ inputs.gh_auth_token }}