apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hmpps-github-actions-runner-security.fullname" . }}
  labels:
    {{- include "hmpps-github-actions-runner-security.labels" . | nindent 4 }}
