name: Cloud Platform Auth
description: Authenticate with MOJ Cloud Platform

inputs:
  api:
    description: The KUBE_ENV_API
    required: true
  cert:
    description: The KUBE_CERT
    required: true
  cluster:
    description: The KUBE_CLUSTER
    required: true
  namespace:
    description: The KUBE_NAMESPACE
    required: true
  token:
    description: The KUBE_TOKEN
    required: true

runs:
  using: composite
  steps:
