name: nvd cache
on:
  schedule:
    - cron:  '0 11 * * *'
  workflow_dispatch:
  # Needed so we can run it manually

jobs:
  build:
    permissions:
      contents: write
    name: Update NVD API Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          ref: gh-pages
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: update
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          curl https://github.com/jeremylong/open-vulnerability-cli/releases/download/v9.0.4/vulnz-9.0.4.jar -s -L -o vulnz.jar
          git reset --soft HEAD~1
          ls -la .
          java -jar vulnz.jar cve --cache --directory ./nvd_cache  --requestCount=30 --debug --delay=8000 --maxRetry=40
          rm vulnz.jar
          git status
          cat nvd_cache/cache.properties
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./nvd_cache/
          git commit -am 'chore: update'
          git push origin gh-pages --force
          cat nvd_cache/nvdcve-modified.meta