name: Deploy runners

on:
  workflow_call:
    inputs:      
      environment:
        description: The name of the environment to deploy to (dev/prod)
        type: string
        required: true
      version:
        description: The image version to deploy
        type: string
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - production
        default: production
      version:
        description: Image version
        type: string
        required: true
        default: 'latest-prod'

jobs:
  deploy:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}  
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/get-env-details
        id: env
        with:
          environment: ${{ inputs.environment }}

      - name: GitHub app installation access token generation
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: generate-github-app-tokens
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ministryofjustice

      - name: Deploy to Platform
        uses: ./.github/actions/cloud-platform-deploy
        with:
          version: ${{ inputs.version }}
          api: https://${{ secrets.KUBE_CLUSTER }}
          cert: ${{ secrets.KUBE_CERT }}
          cluster: ${{ secrets.KUBE_CLUSTER }}
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          token: ${{ secrets.KUBE_TOKEN }}   
          gh_auth_token: ${{ steps.generate-github-app-tokens.outputs.token }}
          github_org: ${{ github.repository_owner }}
          runner_label: ${{ vars.RUNNER_LABEL }}
          runner_group: ${{ vars.RUNNER_GROUP }}
