name: Deploy a runner pod

on:
  workflow_call:
    inputs:      
      environment:
        description: The name of the environment to deploy to (dev/prod)
        type: string
        required: true
      version:
        description: The image version to deploy
        type: string
        required: true
      pod_number:
        description: The pod number to deploy
        type: string
        required: true

  workflow_dispatch:
    inputs:
      pod_number:
        description: The pod number to deploy
        type: choice
        # The pod numbers are hardcoded in the helm chart, so we need to ensure they
        required: true
        options:
          - '1'
          - '2'
          - '3'
          - '4'
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - production
        default: production
      version:
        description: Image version
        type: string
        required: true
        default: 'latest'

jobs:
  deploy:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}  
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/get-env-details
        id: env
        with:
          environment: ${{ inputs.environment }}

      - name: GitHub app JWT and installation access token generation
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        id: generate-github-app-tokens
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Deploy to Platform
        uses: ./.github/actions/cloud-platform-deploy
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.version }}
          pod_number: ${{ inputs.pod_number }}
          api: https://${{ secrets.KUBE_CLUSTER }}
          cert: ${{ secrets.KUBE_CERT }}
          cluster: ${{ secrets.KUBE_CLUSTER }}
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          token: ${{ secrets.KUBE_TOKEN }}   
          gh_auth_token: ${{ steps.generate-github-app-tokens.outputs.access-token }}
          github_org: ${{ github.repository_owner }}
          runner_label: ${{ vars.RUNNER_LABEL }}
          runner_group: ${{ vars.RUNNER_GROUP }}

      - name: Remove offline runners # when the last pod has been deployed
        if: inputs.pod_number == '4' 
        uses: ./.github/actions/runner-cleanup
        with:
          gh_auth_token: ${{ steps.generate-github-app-tokens.outputs.access-token }}
          github_org: ${{ github.repository_owner }}
          runner_label: ${{ vars.RUNNER_LABEL }}

