name: Build -> Deploy pipeline

on:
  push:
    branches:
      - 'main'
      - 'fix/**'
      - 'feat/**'
      - 'feature/**'

  schedule:
    - cron: "30 00,12 * * *"  # Every 12 hours - needs to complete before OWASP scans start from 03:00

  workflow_dispatch:

jobs:
  build-runner:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      packages: write
    name: Build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2.13 # WORKFLOW_VERSION
    with:
      push: true
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      additional_docker_tag: 'latest-prod'
      docker_multiplatform: false
    secrets: inherit

    
  deploy-to-prod:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs:
      - build-runner
    with:
      version: 'latest-prod'
      environment: 'production'
    secrets: inherit
    permissions:
      contents: read
      deployments: write
      pull-requests: write

  runner-cleanup:
    name: Remove old runners
    uses: ./.github/workflows/runner-cleanup.yml
    needs: deploy-to-prod
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write